apiVersion: v1
kind: Service
metadata:
  namespace: profile
  labels:
    app: profile
  name: profile
spec:
  ports:
  
    - protocol: TCP
      port: 8081
      targetPort: 8081
   
   
    - protocol: TCP
      port: 8081
      targetPort: 8081
   
  selector:
    app: profile
  type: ClusterIP
